name: All-In-One Pipeline

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      # cache node mods
      - name: Cache Node-Mods
        uses: actions/cache@v1
        with:
          # where npm caches modules
          path: ~/.npm
          # when package-lock changes, new cache will be generated
          # when OS changes too
          key: ${{ runner.os }}-frontend-cache-key-${{ hashFiles('**/package-lock.json') }}

          # look for cache from previous instance
          restore-key: |
            ${{ runner.os }}-frontend-cache-key-

      # setup node
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.*"

      #  install deps
      - run: npm ci

      # prettier lint check
      - run: npm run format:check

      # run unit tests
      - run: npm run test -- --coverage
        env:
          CI: true

      #
      # Only on push event
      #  Build frontend assets
      #
      - name: Build Frontend Assets
        if: github.event_name == 'push'
        run: npm run build

      #
      # Only on push event
      # Install and run surge
      # Deploy Frontend Repo
      #
      - name: Deploy To Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain ${{secrets.SURGE_DOMAIN}}
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
