name: Multi-Stage All-In-One Pipeline

on:
  pull_request:
    branches: [37-multi-stage-pipeline]
  push:
    branches: [37-multi-stage-pipeline]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      # cache node mods
      - name: Cache Node-Mods
        uses: actions/cache@v1
        with:
          # where npm caches modules
          path: ~/.npm
          # when package-lock changes, new cache will be generated
          # when OS changes too
          key: ${{ runner.os }}-frontend-cache-key-${{ hashFiles('**/package-lock.json') }}

          # look for cache from previous instance
          restore-keys: |
            ${{ runner.os }}-frontend-cache-key-

      # setup node
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.*"

      #  install deps
      - run: npm ci

      # prettier lint check
      - run: npm run format:check

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test -- --coverage
        env:
          CI: true
      - name: Upload CodeCov Report
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx codecov
