name: Notify on Release
on:
  release:
    types: [published]
jobs:
  send-slack-msg:
    runs-on: ubuntu-latest
    steps:
      - name: send slack message through webhook
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "New Release:  ${{ github.event.release.tag_name }} is out, <${{ github.event.release.html_url }}| check it out now>"}' ${{ secrets.SLACK_WEBHOOK_URL }}
