on:
  push:
    branches: ["19"]
jobs:
  test-first-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-js
        id: test-js-step
        with:
          greet-me: "asdf"
      - run: |
          echo "Time: ${{ steps.test-js-step.outputs.time }}"
